sensor:
# Statistiques Temperature exterieure
# sert à rien: garder pour exemple
  - platform: statistics
    entity_id: sensor.vp2_temp_out
    max_age:
      minutes: 1440 #24h
    name: stats_temperature_exterieure
  - platform: template
    sensors:
      exterieure_temp_min:
        value_template: "{{ state_attr('sensor.stats_temperature_Exterieure', 'min_value') }}" 
      exterieure_temp_max:
        value_template: "{{ state_attr('sensor.stats_temperature_exterieure', 'max_value') }}" 
      exterieure_temp_moyenne:
        value_template: "{{ state_attr('sensor.stats_temperature_exterieure', 'median') }}" 

