entities:
  - entity: input_select.pool_pump_mode
    name: Mode de Fonctionnement
  - entities:
      - entity: sensor.pression_piscine_p
        name: Pression
      - entity: sensor.temp_piscine
        name: T Eau
      - entity: sensor.pool_water_temperature
        name: T° At
      - entity: sensor.vp2_temp_out
        name: T Ext
    entity: sensor.pression_piscine_p
    icon: mdi:chart-bell-curve
    name: Mesures
    show_state: false
    type: custom:multiple-entity-row
  - entities:
      - entity: switch.cde_traitement
        name: Ppe
      - entity: input_boolean.regul_ph
        name: Val Ph
      - entity: sensor.ph_ezo
        name: Ezo
        unit: false
      - entity: sensor.ph_piscine_ph
        name: Filtré
        unit: false
      - entity: input_number.ph_cible
        name: Cible
        unit: false
      - entity: sensor.ph_volume_restant_bidon
        name: Vol Bid
        unit: false
    entity: input_boolean.regul_ph
    icon: mdi:chart-bell-curve
    name: Ph
    show_state: false
    type: custom:multiple-entity-row
  - entities:
      - entity: switch.cde_ppe_chlore
        name: Ppe
      - entity: input_boolean.regul_chlore
        name: Val Ph
      - entity: sensor.orp_ezo
        name: Ezo
        unit: false
      - entity: sensor.orp_piscine_orp
        name: Filtré
        unit: false
      - entity: input_number.chlore_cible
        name: Cible
        unit: false
      - entity: sensor.chlore_volume_restant_bidon
        name: Vol Bid
        unit: false
    entity: input_boolean.regul_chlore
    icon: mdi:chart-bell-curve
    name: Chlore/ORP
    show_state: false
    type: custom:multiple-entity-row
  - entities:
      - entity: input_number.temps_cartouche_chlore
        name: Tps Cartouche
        unit: false
      - entity: input_number.chlore_seuil_max_utilisation
        name: Tps Max
    entity: input_number.temps_cartouche_chlore
    icon: mdi:chart-bell-curve
    name: Chlore cart
    show_state: false
    type: custom:multiple-entity-row
  - entities:
      - entity: pool_pump.next_run_schedule
        name: 'A venir '
      - entity: sensor.heure_pivot_piscine
        name: Heure pivot
    entity: pool_pump.next_run_schedule
    icon: mdi:clock
    name: Tranche horaire
    show_state: false
    type: custom:multiple-entity-row
  - entities:
      - entity: sensor.pool_pump_running_today
        name: Fonct. Jour
      - entity: binary_sensor.pool_pump_running
        name: Etat
    entity: sensor.pool_pump_running_today
    icon: mdi:pump
    name: Pompe Filtration
    show_state: false
    type: custom:multiple-entity-row
  - entities:
      - entity: sensor.pzem_pisc_puissance
        name: Puissance
      - entity: sensor.pzem_pisc_courant
        name: Intensité
    entity: sensor.pzem_pisc_puissance
    icon: mdi:flash
    name: Conso Elec
    show_state: false
    type: custom:multiple-entity-row
  - entities:
      - entity: input_boolean.piscine_mode_hivernage
      - entity: input_datetime.heure_ma_pump_pisc_hiv
        name: MaPpe
      - entity: input_datetime.heure_at_pump_pisc_hiv
        name: AtPpe
      - entity: input_boolean.hors_gel
        name: HG si actif
      - entity: input_number.hors_gel_inf
        name: T°Inf
      - entity: input_number.hors_gel_sup
        name: T°Sup
    entity: input_boolean.hors_gel
    icon: mdi:snowflake-alert
    name: Hiver
    show_state: false
    type: custom:multiple-entity-row
  - entities:
      - entity: input_boolean.volet_piscine_auto
        name: Auto
      - entity: cover.volet_piscine
        name: Volet
      - entity: input_datetime.heure_ouv_volet_pisc
        name: Ouv
      - entity: input_datetime.heure_ferm_volet_pisc
        name: Ferm
    entity: cover.volet_piscine
    icon: mdi:window-shutter
    name: Volet piscine
    show_state: false
    type: custom:multiple-entity-row
  - entities:
      - entity: sensor.ev_eau_sur_7j
        name: 7J
      - entity: sensor.ev_eau_tps_ouverture_jour
        name: 1J
      - entity: switch.cde_ev_eau
        name: Cde EV
      - entity: binary_sensor.tp_plein_lsh
        name: Niv H
      - entity: binary_sensor.tp_plein_lsl
        name: Niv B
    entity: sensor.ev_eau_tps_ouverture_jour
    icon: mdi:water
    name: Appoint Eau
    show_state: false
    type: custom:multiple-entity-row
  - entities:
      - label: Filtration
        type: section
      - entity: input_number.mem_temp_piscine
      - label: Volet
        type: section
      - entity: input_boolean.volet_piscine_auto
      - entity: input_datetime.heure_ouv_volet_pisc
      - entity: input_datetime.heure_ferm_volet_pisc
      - label: Hiver
        type: section
      - entity: input_boolean.piscine_mode_hivernage
      - entity: input_datetime.heure_ma_pump_pisc_hiv
        name: Heure Marche Ppe
      - entity: input_datetime.heure_at_pump_pisc_hiv
        name: Heure Arret Ppe
      - entity: input_boolean.hors_gel
        name: Hors Gel si Actif
      - entity: input_number.hors_gel_inf
      - entity: input_number.hors_gel_sup
      - label: Chlore
        type: section
      - entity: input_number.temps_cartouche_chlore
      - entity: input_number.chlore_seuil_max_utilisation
      - label: pH
        type: section
      - entity: sensor.ph_ezo
        name: pH Ezo
      - entity: sensor.ph_piscine_ph
        name: pH filtré
      - entity: input_number.ph_memoire
      - entity: sensor.ph_stat
        name: pH Statistiques
      - entity: input_boolean.regul_ph
      - entity: input_number.ph_cible
      - entity: input_number.ph_hysteresis
      - entity: sensor.ph_derniere_heure
      - entity: sensor.ph_derniere_48h
      - entity: input_number.ph_debit_ppe
      - entity: input_number.ph_concentration
      - entity: input_number.ph_vol_bidon
      - entity: input_number.ph_seuil_bas_bidon
      - entity: input_number.ph_vol_injecte
      - entity: binary_sensor.ph_niveau_bas_bidon
      - entity: sensor.ph_tps_inject_mn
      - entity: sensor.ph_tps_inject_s
      - entity: input_number.ph_duree_inject_mn
      - entity: input_number.ph_duree_inject_s
      - label: Chlore/ORP
        type: section
      - entity: sensor.orp_ezo
        name: ORP Ezo
      - entity: sensor.orp_piscine_orp
        name: ORP filtré
      - entity: input_number.orp_memoire
      - entity: sensor.orp_stat
        name: ORP Statistiques
      - entity: input_boolean.regul_chlore
      - entity: input_number.orp_cible
      - entity: input_number.orp_hysteresis
      - entity: sensor.chlore_derniere_heure
      - entity: sensor.chlore_derniere_48h
      - entity: input_number.chlore_debit_ppe
      - entity: input_number.chlore_concentration
      - entity: input_number.chlore_vol_bidon
      - entity: input_number.chlore_seuil_bas_bidon
      - entity: input_number.chlore_vol_injecte
      - entity: binary_sensor.chlore_niveau_bas_bidon
      - entity: sensor.chlore_tps_inject_mn
      - entity: sensor.chlore_tps_inject_s
      - entity: input_number.chlore_duree_inject_mn
      - entity: input_number.chlore_duree_inject_s
      - label: Commutateurs
        type: section
      - entity: cover.volet_piscine
        name: Couverture flottante
      - entity: input_boolean.eclairage_piscine
        name: Eclairage
      - entity: input_boolean.ev_eau_piscine
        name: EV Eau appoint en auto si actif
    show_state: false
    head:
      label: PARAMETRES & COMMUTATEURS
      type: section
    padding: 0
    type: custom:fold-entity-row
  - entities:
      - entity: switch.pool_pump_switch
        name: Relais Pompe Filtre
      - entity: switch.cde_traitement
        name: Relais pH
      - entity: switch.cde_ppe_chlore
        name: Relais Chlore
      - entity: switch.cde_volet_ouverture
        name: Relais Ouverture Volet
      - entity: switch.cde_volet_fermeture
        name: Relais fermeture Volet
      - entity: switch.cde_eclairage
        name: Relais Eclairage
      - entity: switch.cde_ev_eau
        name: EV Eau
    show_state: false
    head:
      label: COMMANDES DIRECTES
      type: section
    padding: 0
    type: custom:fold-entity-row
style: |
  ha-card {
    border: solid 2px var(--primary-color);
  }
show_header_toggle: false
title: Piscine
type: entities
